sudo: true
language: python
python:
  - 3.5
  - 3.6

env:
  - FLASK=0.12.2

install:

  - pip install python-coveralls
  - pip install coveralls
  - pip install coverage
  - pip install nose
  - pip install Flask==$FLASK

  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE test_bucket_list;" -U postgres
  - psql -c "CREATE USER bucket_list WITH PASSWORD 'bucket_list';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test_bucket_list TO bucket_list;" -U postgres
  - python manage.py db upgrade

script: nosetests --with-coverage

after_success:
  - coveralls
